-- Additive fields required by the production admin dashboard.
ALTER TABLE "ProductVariant" ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "InventoryAdjustment" ADD COLUMN "internalNote" TEXT;
ALTER TABLE "WholesaleApplication" ADD COLUMN "internalNotes" TEXT;
ALTER TABLE "WholesaleApplication" ADD COLUMN "reviewedAt" TIMESTAMP(3);
ALTER TABLE "WholesaleApplication" ADD COLUMN "city" TEXT;
ALTER TABLE "WholesaleApplication" ADD COLUMN "postalCode" TEXT;
ALTER TABLE "WholesaleApplication" ADD COLUMN "countryCode" TEXT NOT NULL DEFAULT 'DE';
ALTER TABLE "WholesaleApplication" ADD COLUMN "preferredContactMethod" TEXT;
ALTER TABLE "WholesaleApplication" ADD COLUMN "accuracyConfirmedAt" TIMESTAMP(3);
ALTER TABLE "ContactEnquiry" ADD COLUMN "subject" TEXT;
ALTER TABLE "ContactEnquiry" ADD COLUMN "preferredContactMethod" TEXT;
ALTER TABLE "ContactEnquiry" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'NEW';
ALTER TABLE "ContactEnquiry" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "GiftBox" ADD COLUMN "slugDe" TEXT;
ALTER TABLE "GiftBox" ADD COLUMN "slugEn" TEXT;
ALTER TABLE "GiftBox" ADD COLUMN "seoTitleDe" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GiftBox" ADD COLUMN "seoTitleEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GiftBox" ADD COLUMN "metaDescriptionDe" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GiftBox" ADD COLUMN "metaDescriptionEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GiftBox" ADD COLUMN "imageUrl" TEXT;
ALTER TABLE "GiftBox" ADD COLUMN "sizeName" TEXT NOT NULL DEFAULT 'MEDIUM';
UPDATE "GiftBox" SET "slugDe" = 'geschenkbox-' || "id", "slugEn" = 'gift-box-' || "id" WHERE "slugDe" IS NULL;
ALTER TABLE "GiftBox" ALTER COLUMN "slugDe" SET NOT NULL;
ALTER TABLE "GiftBox" ALTER COLUMN "slugEn" SET NOT NULL;
CREATE UNIQUE INDEX "GiftBox_slugDe_key" ON "GiftBox"("slugDe");
CREATE UNIQUE INDEX "GiftBox_slugEn_key" ON "GiftBox"("slugEn");

CREATE TABLE "GiftPackagingOption" ("id" TEXT NOT NULL, "nameDe" TEXT NOT NULL, "nameEn" TEXT NOT NULL, "descriptionDe" TEXT, "descriptionEn" TEXT, "priceCents" INTEGER NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "GiftPackagingOption_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GiftBoxConfiguration" ("id" TEXT NOT NULL, "giftBoxId" TEXT NOT NULL, "userId" TEXT, "guestToken" TEXT, "sizeName" TEXT NOT NULL, "capacityUnits" INTEGER NOT NULL, "packagingOptionId" TEXT, "giftMessage" TEXT, "occasion" TEXT, "itemsTotalCents" INTEGER NOT NULL, "boxChargeCents" INTEGER NOT NULL, "packagingCents" INTEGER NOT NULL, "totalCents" INTEGER NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "GiftBoxConfiguration_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GiftBoxConfigurationItem" ("id" TEXT NOT NULL, "configurationId" TEXT NOT NULL, "productId" TEXT NOT NULL, "variantId" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "capacityUnits" INTEGER NOT NULL DEFAULT 1, "unitPriceCents" INTEGER NOT NULL, CONSTRAINT "GiftBoxConfigurationItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CartGiftBoxItem" ("id" TEXT NOT NULL, "cartId" TEXT NOT NULL, "configurationId" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CartGiftBoxItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OrderGiftBoxItem" ("id" TEXT NOT NULL, "orderId" TEXT NOT NULL, "configurationId" TEXT, "giftBoxName" TEXT NOT NULL, "sizeName" TEXT NOT NULL, "packagingName" TEXT, "giftMessage" TEXT, "occasion" TEXT, "quantity" INTEGER NOT NULL, "unitPriceCents" INTEGER NOT NULL, "totalCents" INTEGER NOT NULL, "snapshot" JSONB NOT NULL, CONSTRAINT "OrderGiftBoxItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProductSearchAlias" ("id" TEXT NOT NULL, "productId" TEXT NOT NULL, "locale" "Locale" NOT NULL, "alias" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ProductSearchAlias_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "GiftBoxConfigurationItem_configurationId_variantId_key" ON "GiftBoxConfigurationItem"("configurationId", "variantId");
CREATE UNIQUE INDEX "CartGiftBoxItem_configurationId_key" ON "CartGiftBoxItem"("configurationId");
CREATE UNIQUE INDEX "ProductSearchAlias_productId_locale_alias_key" ON "ProductSearchAlias"("productId", "locale", "alias");
CREATE INDEX "ProductSearchAlias_locale_alias_idx" ON "ProductSearchAlias"("locale", "alias");
ALTER TABLE "GiftBoxConfiguration" ADD CONSTRAINT "GiftBoxConfiguration_giftBoxId_fkey" FOREIGN KEY ("giftBoxId") REFERENCES "GiftBox"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GiftBoxConfiguration" ADD CONSTRAINT "GiftBoxConfiguration_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "GiftBoxConfiguration" ADD CONSTRAINT "GiftBoxConfiguration_packagingOptionId_fkey" FOREIGN KEY ("packagingOptionId") REFERENCES "GiftPackagingOption"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "GiftBoxConfigurationItem" ADD CONSTRAINT "GiftBoxConfigurationItem_configurationId_fkey" FOREIGN KEY ("configurationId") REFERENCES "GiftBoxConfiguration"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GiftBoxConfigurationItem" ADD CONSTRAINT "GiftBoxConfigurationItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GiftBoxConfigurationItem" ADD CONSTRAINT "GiftBoxConfigurationItem_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "ProductVariant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CartGiftBoxItem" ADD CONSTRAINT "CartGiftBoxItem_cartId_fkey" FOREIGN KEY ("cartId") REFERENCES "Cart"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CartGiftBoxItem" ADD CONSTRAINT "CartGiftBoxItem_configurationId_fkey" FOREIGN KEY ("configurationId") REFERENCES "GiftBoxConfiguration"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OrderGiftBoxItem" ADD CONSTRAINT "OrderGiftBoxItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderGiftBoxItem" ADD CONSTRAINT "OrderGiftBoxItem_configurationId_fkey" FOREIGN KEY ("configurationId") REFERENCES "GiftBoxConfiguration"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProductSearchAlias" ADD CONSTRAINT "ProductSearchAlias_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
