import type { Category, Product, ProductTranslation } from "@generated/prisma/client";
import { AdminForm } from "./admin-form";

type ProductWithTranslations = Product & { translations: ProductTranslation[]; categories: { categoryId: string }[] };
export function ProductForm({ product, categories, action }: { product?: ProductWithTranslations; categories: (Category & { translations: ProductTranslationLike[] })[]; action: (formData: FormData) => Promise<{ success: boolean; error?: { message: string; fieldErrors?: Record<string, string[]> } } | void> }) {
  const de = product?.translations.find((item) => item.locale === "de"); const en = product?.translations.find((item) => item.locale === "en");
  return <AdminForm action={action} submitLabel={product ? "Save draft changes" : "Create draft product"}>
    {product && <input type="hidden" name="productId" value={product.id} />}
    <AdminSection title="Basic details" description="Internal identification and storefront flags."><div className="admin-field-grid"><Field label="Internal name" name="internalName" required defaultValue={product?.internalName} /><SelectField label="Primary category" name="categoryId" required defaultValue={product?.categories[0]?.categoryId} options={categories.map((category) => ({ value: category.id, label: category.translations.find((item) => item.locale === "en")?.name ?? category.internalName }))} /><Field label="Country of origin" name="countryOfOrigin" defaultValue={product?.countryOfOrigin ?? ""} /><Field label="Region of origin" name="regionOfOrigin" defaultValue={product?.regionOfOrigin ?? ""} /><Field label="Responsible food business" name="responsibleFoodBusiness" defaultValue={product?.responsibleFoodBusiness ?? ""} wide /><Checkbox name="featured" label="Featured product" defaultChecked={product?.featured} /><Checkbox name="bestseller" label="Bestseller" defaultChecked={product?.bestseller} /><Checkbox name="newProduct" label="New product" defaultChecked={product?.newProduct} /><Checkbox name="giftSuitable" label="Suitable for gifts" defaultChecked={product?.giftSuitable} /></div></AdminSection>
    <AdminSection title="German content" description="Required for German publication. No English fallback is used."><div className="admin-field-grid"><Field label="German name" name="nameDe" required defaultValue={de?.name} /><Field label="German slug" name="slugDe" required defaultValue={de?.slug} /><TextField label="Short description" name="shortDescriptionDe" defaultValue={de?.shortDescription} /><TextField label="Full description" name="descriptionDe" defaultValue={de?.description} rows={6} /><TextField label="Ingredients" name="ingredientsDe" defaultValue={de?.ingredients} /><TextField label="Allergen information" name="allergenDe" defaultValue={de?.allergenStatement} /><TextField label="Storage instructions" name="storageDe" defaultValue={de?.storageInstructions} /></div></AdminSection>
    <AdminSection title="English content" description="Leave incomplete rather than copying German content."><div className="admin-field-grid"><Field label="English name" name="nameEn" defaultValue={en?.name} /><Field label="English slug" name="slugEn" defaultValue={en?.slug} /><TextField label="Short description" name="shortDescriptionEn" defaultValue={en?.shortDescription} /><TextField label="Full description" name="descriptionEn" defaultValue={en?.description} rows={6} /><TextField label="Ingredients" name="ingredientsEn" defaultValue={en?.ingredients} /><TextField label="Allergen information" name="allergenEn" defaultValue={en?.allergenStatement} /><TextField label="Storage instructions" name="storageEn" defaultValue={en?.storageInstructions} /></div></AdminSection>
    <AdminSection title="Search engine information" description="Separate metadata is stored for each locale."><div className="admin-field-grid"><Field label="German SEO title" name="seoTitleDe" defaultValue={de?.seoTitle} /><Field label="English SEO title" name="seoTitleEn" defaultValue={en?.seoTitle} /><TextField label="German meta description" name="metaDescriptionDe" defaultValue={de?.metaDescription} /><TextField label="English meta description" name="metaDescriptionEn" defaultValue={en?.metaDescription} /></div></AdminSection>
  </AdminForm>;
}

type ProductTranslationLike = { locale: "de" | "en"; name: string };
export function AdminSection({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="admin-form-section"><header><h2>{title}</h2>{description && <p>{description}</p>}</header>{children}</section>; }
export function Field({ label, name, defaultValue, required, type = "text", wide, min, max }: { label: string; name: string; defaultValue?: string | number | null; required?: boolean; type?: string; wide?: boolean; min?: number; max?: number }) { return <label className={wide ? "admin-field wide" : "admin-field"}><span>{label}{required && <b aria-hidden="true"> *</b>}</span><input name={name} defaultValue={defaultValue ?? ""} required={required} type={type} min={min} max={max} /></label>; }
export function TextField({ label, name, defaultValue, rows = 3 }: { label: string; name: string; defaultValue?: string | null; rows?: number }) { return <label className="admin-field wide"><span>{label}</span><textarea name={name} defaultValue={defaultValue ?? ""} rows={rows} /></label>; }
export function SelectField({ label, name, options, defaultValue, required }: { label: string; name: string; options: { value: string; label: string }[]; defaultValue?: string; required?: boolean }) { return <label className="admin-field"><span>{label}</span><select name={name} defaultValue={defaultValue} required={required}><option value="">Select…</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
export function Checkbox({ name, label, defaultChecked }: { name: string; label: string; defaultChecked?: boolean }) { return <label className="admin-checkbox"><input type="checkbox" name={name} value="true" defaultChecked={defaultChecked} /><span>{label}</span></label>; }
